;;; word_chars_org_9_7_11.el --- characters org reads as part of a word before `src_'  -*- lexical-binding: t -*-

;; Writes `word_chars_org_9_7_11.rs'. Run from its directory (about 6 minutes):
;;   emacs -Q --batch -l word_chars_org_9_7_11.el
;;
;; The file is a Rust array of inclusive character ranges: the characters C
;; for which `\<' does not match between C and `src' in an org-mode buffer,
;; so `C' followed by `src_' or `call_' starts no inline source block or call.

(require 'org)

(with-temp-buffer
  (org-mode)
  (let ((ranges nil) (start nil))
    (dotimes (c (1+ (max-char t)))
      (let ((in-word (and (not (<= #xd800 c #xdfff))
                          (progn (erase-buffer)
                                 (insert (string c) "src")
                                 (goto-char 2)
                                 (not (looking-at-p "\\<src"))))))
        (cond ((and in-word (not start)) (setq start c))
              ((and (not in-word) start)
               (push (cons start (1- c)) ranges)
               (setq start nil)))))
    (when start (push (cons start (max-char t)) ranges))
    (with-temp-file "word_chars_org_9_7_11.rs"
      (insert "// Generated by word_chars_org_9_7_11.el; do not edit.\n[\n")
      (dolist (r (nreverse ranges))
        (insert (format "    ('\\u{%x}', '\\u{%x}'),\n" (car r) (cdr r))))
      (insert "]\n"))))
